-- 1
DECLARE
   PROCEDURE GET_TEACHERS (PCODE TEACHER.PULPIT%TYPE) IS
   BEGIN
      FOR rec IN (SELECT TEACHER_NAME, PULPIT
                  FROM TEACHER
                  WHERE PULPIT = PCODE) LOOP
         DBMS_OUTPUT.PUT_LINE('Teacher: ' || rec.TEACHER_NAME || ' Pulpit: ' || rec.PULPIT);
      END LOOP;
   END GET_TEACHERS;
BEGIN
   GET_TEACHERS('ИСиТ');
END;

-- 2
DECLARE
   FUNCTION GET_TEACHERS (PCODE TEACHER.PULPIT%TYPE) RETURN VARCHAR2 IS
      v_result VARCHAR2(4000);
   BEGIN
      v_result := '';
      FOR rec IN (SELECT TEACHER_NAME, PULPIT
                  FROM TEACHER
                  WHERE PULPIT = PCODE) LOOP
         v_result := v_result || 'Teacher: ' || rec.TEACHER_NAME || ' Pulpit: ' || rec.PULPIT || CHR(10);
      END LOOP;
      RETURN v_result;
   END GET_TEACHERS;
BEGIN
   DBMS_OUTPUT.PUT_LINE(GET_TEACHERS('ИСиТ'));
END;

-- 3
DECLARE
    v_num_teachers NUMBER := 0;

    FUNCTION GET_NUM_TEACHERS(PCODE TEACHER.PULPIT%TYPE) RETURN NUMBER IS
    BEGIN
        FOR rec IN (SELECT TEACHER_NAME, PULPIT
                    FROM TEACHER
                    WHERE PULPIT = PCODE) LOOP
            v_num_teachers := v_num_teachers + 1;
        END LOOP;
        RETURN v_num_teachers;
    END GET_NUM_TEACHERS;
BEGIN
    DBMS_OUTPUT.PUT_LINE('Количество преподавателей: ' || GET_NUM_TEACHERS('ИСиТ'));
END;

-- 4
DECLARE
  PROCEDURE GET_TEACHERS(FCODE FACULTY.FACULTY%TYPE) IS
  BEGIN
    FOR rec IN (
      SELECT t.TEACHER_NAME, f.FACULTY
      FROM TEACHER t
      JOIN PULPIT p ON t.PULPIT = p.PULPIT
      JOIN FACULTY f ON p.FACULTY = f.FACULTY
      WHERE f.FACULTY = FCODE
    ) LOOP
      DBMS_OUTPUT.PUT_LINE('Преподаватель: ' || rec.TEACHER_NAME || ' Факультет: ' || rec.FACULTY);
    END LOOP;
  END GET_TEACHERS;
BEGIN
  GET_TEACHERS('ТОВ');
END;

-- 5
DECLARE
  PROCEDURE GET_SUBJECTS(PCODE SUBJECT.PULPIT%TYPE) IS
  BEGIN
    FOR rec IN (
      SELECT SUBJECT_NAME, PULPIT
      FROM SUBJECT
      WHERE PULPIT = PCODE
    ) LOOP
      DBMS_OUTPUT.PUT_LINE('Дисциплина: ' || rec.SUBJECT_NAME || ' Кафедра: ' || rec.PULPIT);
    END LOOP;
  END GET_SUBJECTS;
BEGIN
  GET_SUBJECTS('ИСиТ');
END;

-- 6
DECLARE
  FUNCTION GET_NUM_TEACHERS(FCODE FACULTY.FACULTY%TYPE) RETURN NUMBER IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM TEACHER T
    JOIN PULPIT P ON T.PULPIT = P.PULPIT
    WHERE P.FACULTY = FCODE;
    RETURN v_count;
  END GET_NUM_TEACHERS;
BEGIN
  DBMS_OUTPUT.PUT_LINE('Количество преподавателей: ' || GET_NUM_TEACHERS('ТОВ'));
END;

-- 7
DECLARE
  FUNCTION GET_NUM_SUBJECTS(PCODE SUBJECT.PULPIT%TYPE) RETURN NUMBER IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM SUBJECT
    WHERE PULPIT = PCODE;
    RETURN v_count;
  END GET_NUM_SUBJECTS;

BEGIN
  DBMS_OUTPUT.PUT_LINE('Количество дисциплин: ' || GET_NUM_SUBJECTS('ИСиТ'));
END;

--8
CREATE OR REPLACE PACKAGE TEACHERS_PACKAGE AS
  PROCEDURE GET_TEACHERS(FCODE FACULTY.FACULTY%TYPE);
  PROCEDURE GET_SUBJECTS(PCODE SUBJECT.PULPIT%TYPE);
  FUNCTION GET_NUM_TEACHERS(FCODE FACULTY.FACULTY%TYPE) RETURN NUMBER;
  FUNCTION GET_NUM_SUBJECTS(PCODE SUBJECT.PULPIT%TYPE) RETURN NUMBER;
END TEACHERS_PACKAGE;

CREATE OR REPLACE PACKAGE BODY TEACHERS_PACKAGE AS
  PROCEDURE GET_TEACHERS(FCODE FACULTY.FACULTY%TYPE) IS
  BEGIN
    FOR rec IN (
        SELECT t.TEACHER_NAME
        FROM TEACHER t
            JOIN PULPIT P on P.PULPIT = t.PULPIT
            JOIN FACULTY F on F.FACULTY = P.FACULTY
        WHERE F.FACULTY = FCODE) LOOP
      DBMS_OUTPUT.PUT_LINE('Преподаватель: ' || rec.TEACHER_NAME);
    END LOOP;
  END GET_TEACHERS;

  PROCEDURE GET_SUBJECTS(PCODE SUBJECT.PULPIT%TYPE) IS
  BEGIN
    FOR rec IN (SELECT SUBJECT_NAME FROM SUBJECT WHERE PULPIT = PCODE) LOOP
      DBMS_OUTPUT.PUT_LINE('Дисциплина: ' || rec.SUBJECT_NAME);
    END LOOP;
  END GET_SUBJECTS;

  FUNCTION GET_NUM_TEACHERS(FCODE FACULTY.FACULTY%TYPE) RETURN NUMBER IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM TEACHER
        JOIN PULPIT P2 on P2.PULPIT = TEACHER.PULPIT
        JOIN FACULTY F2 on F2.FACULTY = P2.FACULTY
    WHERE F2.FACULTY = FCODE;
    RETURN v_count;
  END GET_NUM_TEACHERS;

  FUNCTION GET_NUM_SUBJECTS(PCODE SUBJECT.PULPIT%TYPE) RETURN NUMBER IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_count FROM SUBJECT WHERE PULPIT = PCODE;
    RETURN v_count;
  END GET_NUM_SUBJECTS;
END TEACHERS_PACKAGE;


BEGIN
    TEACHERS_PACKAGE.GET_TEACHERS('ТОВ');
        DBMS_OUTPUT.PUT_LINE('-----------------------------------');
    TEACHERS_PACKAGE.GET_SUBJECTS('ИСиТ');
        DBMS_OUTPUT.PUT_LINE('-----------------------------------');
    DBMS_OUTPUT.PUT_LINE('Количество преподавателей: ' || TEACHERS_PACKAGE.GET_NUM_TEACHERS('ТОВ'));
        DBMS_OUTPUT.PUT_LINE('-----------------------------------');
    DBMS_OUTPUT.PUT_LINE('Количество дисциплин: ' || TEACHERS_PACKAGE.GET_NUM_SUBJECTS('ИСиТ'));
END;